@baseURL = http://localhost:3333

# @name registerTask
PUT {{baseURL}}/tasks/6d56c6bb-1f2b-45f0-be32-1418a7c9add1
Content-Type: application/json

{
  "title": "Example 3",
  "description": "Example 4"
}
