@baseURL = http://localhost:3333

# @name fetchAllTasks
GET {{baseURL}}/tasks

###

# @name filterTasksByTileOrDescription
GET {{baseURL}}/tasks?title=Example

###

# @name filterTasksByTileAndDescription
GET {{baseURL}}/tasks?description=Example&title='Anythingelse'

###

# @name registerTask
POST {{baseURL}}/tasks
Content-Type: application/json

{
  "title": "Anythingelse",
  "description": "Example"
}

###

# @name deleteById
DELETE {{baseURL}}/tasks/6d56c6bb-1f2b-45f0-be32-1418a7c9add1
