@baseURL = http://localhost:3333

# @name fetchAllTasks
GET {{baseURL}}/tasks

###

# @name filterTasksByTileOrDescription
GET {{baseURL}}/tasks?title=Example

###

# @name filterTasksByTileAndDescription
GET {{baseURL}}/tasks?description=Example&title='Anythingelse'

###

# @name registerTask
POST {{baseURL}}/tasks
Content-Type: application/json

{
  "title": "Anythingelse",
  "description": "Example"
}
